#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np

data = {
    'Country': ['USA', 'USA', 'China', 'China', 'Germany', 'Germany'],
    'Year': [2020, 2021, 2020, 2021, 2020, 2021],
    'Population': [331000000, 332000000, 1402000000, 1405000000, 83000000, 83100000],
    'GDP': [21000000, 21500000, 14700000, 15500000, 4000000, 4200000],
    'Life_Expectancy': [78.5, 78.7, 76.9, 77.1, 81.3, 81.5]
}

df = pd.DataFrame(data)
df.set_index(['Country', 'Year'], inplace=True)
print("Original DataFrame:\n", df, "\n")

print("Mean Population:", df['Population'].mean())
print("Sum GDP:", df['GDP'].sum())
print("Max GDP:", df['GDP'].max())
print("Min GDP:", df['GDP'].min())

# Using numpy
print("Numpy Mean GDP:", np.mean(df['GDP']))
print("Numpy Std Population:", np.std(df['Population']))
print("Numpy Sum Population:", np.sum(df['Population']), "\n")


df['GDP'] = df['GDP'] * 1.10
print("After 10% GDP Increase:\n", df, "\n")


swapped = df.swaplevel('Country', 'Year').sort_index(level='Year')
print("After swaplevel and sort by Year:\n", swapped, "\n")


unstacked = df[['GDP', 'Life_Expectancy']].unstack(level='Year')
print("Unstacked Data (Years as Columns):\n", unstacked, "\n")

print("Population trend for China:\n", df.loc['China', 'Population'])


# In[2]:


import pandas as pd

# Sample Dataset
data = {
    'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-03',
             '2024-01-04', '2024-01-04', '2024-01-05'],
    'Region': ['North', 'North', 'South', 'East', 'West', 'South', 'East'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Charlie', 'Alice'],
    'Product': ['Widget A', 'Widget B', 'Widget A', 'Widget B', 'Widget B', 'Widget A', 'Widget B'],
    'Units Sold': [10, 8, 15, 12, 9, 10, 9],
    'Price per Unit': [20, 30, 20, 20, 30, 30, 30]
}

# Create DataFrame
df = pd.DataFrame(data)
df['Revenue'] = df['Units Sold'] * df['Price per Unit']
print("Original Dataset:\n", df, "\n")


pivot1 = pd.pivot_table(df, values='Revenue', index='Date', columns='Salesperson', aggfunc='sum', fill_value=0)
print("1. Total revenue generated by each salesperson on each date:\n", pivot1, "\n")


avg_revenue = df.groupby('Product')['Revenue'].mean()
print("2. Average revenue per sale for each product:\n", avg_revenue, "\n")


max_units = df.groupby('Salesperson')['Units Sold'].max()
print("3. Maximum units sold in a single transaction by each salesperson:\n", max_units, "\n")


region_revenue = df.groupby('Region')['Revenue'].sum()
percent_region = (region_revenue / region_revenue.sum()) * 100
print("4. Percentage of total revenue by each region:\n", percent_region, "\n")

sales_count = df['Salesperson'].value_counts()
top_salesperson = sales_count.idxmax()
print("5. Salesperson with most sales transactions:", top_salesperson, "\n")
print("   Transaction counts:\n", sales_count, "\n")


pivot2 = pd.pivot_table(df, index='Salesperson', columns='Product',
                        values=['Revenue', 'Units Sold'], aggfunc='sum', fill_value=0)
print("6. Total revenue and total units sold by each salesperson for each product:\n", pivot2, "\n")


pivot3 = pd.pivot_table(df, values='Units Sold', index='Date', columns='Region', aggfunc='sum', fill_value=0)
print("7. Total units sold in each region on each date:\n", pivot3, "\n")


# In[ ]:




